/**
 * Drizzle schema — the canonical Postgres model.
 *
 * Conventions
 * -----------
 * - Every table has `id` (text, ULID), `created_at`, `updated_at`. Tables that hold
 *   health-special-category data also have `deleted_at` (soft delete; KVKK Article 7
 *   right-to-erasure handled via `purgeForDsar()` job, not raw DELETE).
 * - All FKs are explicit; `onDelete: 'restrict'` by default. Only `onDelete: 'cascade'`
 *   where the child has no independent meaning (e.g., translations of a content entry).
 * - Money values: never used here (no payments in MVP).
 * - Phone: stored as E.164 in `text`; validation enforced at the domain boundary.
 * - Locale: enum `tr | ar | en | fr | es`.
 * - Timestamps: `timestamptz` UTC. The clinic local timezone (Europe/Istanbul) is a
 *   *display* concern handled in the application layer.
 *
 * Migrations live next to this file in `./migrations/`. Generated by `pnpm db:generate`.
 */

import { sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  boolean,
  customType,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// ─── Enums ─────────────────────────────────────────────────────────────────────

export const localeEnum = pgEnum('locale', ['tr', 'ar', 'en', 'fr', 'es']);

export const roleEnum = pgEnum('role', ['patient', 'staff', 'admin', 'doctor']);

export const deliveryModeEnum = pgEnum('delivery_mode', ['in_person', 'home_visit', 'telehealth']);

export const slotKindEnum = pgEnum('slot_kind', [
  'consultation_30',
  'consultation_15',
  'tms_session_45',
  'iv_therapy_60',
  'home_visit_90',
]);

export const appointmentStatusEnum = pgEnum('appointment_status', [
  'created',
  'confirmed',
  'rescheduled',
  'cancelled_by_patient',
  'cancelled_by_clinic',
  'late_cancellation',
  'no_show',
  'completed',
]);

export const consentPurposeEnum = pgEnum('consent_purpose', [
  'appointment_booking',
  'health_data_processing',
  'testimonial_publication',
  'marketing_communications',
  'document_storage',
  'guardian_consent',
  'video_consultation_recording',
  'tms_screening_data',
]);

export const documentMimeKindEnum = pgEnum('document_mime_kind', [
  'image',
  'pdf',
  'dicom',
  'text',
  'other',
]);

export const documentScanStatusEnum = pgEnum('document_scan_status', [
  'pending',
  'clean',
  'infected',
  'failed',
]);

export const testimonialStatusEnum = pgEnum('testimonial_status', [
  'submitted',
  'approved',
  'rejected',
  'retracted',
]);

export const contentEntryTypeEnum = pgEnum('content_entry_type', [
  'blog',
  'condition',
  'service',
  'faq',
  'guide',
  'legal',
]);

export const contentEntryStatusEnum = pgEnum('content_entry_status', [
  'draft',
  'review',
  'published',
  'archived',
]);

export const tmsScreeningStatusEnum = pgEnum('tms_screening_status', [
  'pending_review',
  'cleared',
  'requires_review',
  'denied',
  'expired',
]);

export const auditActionEnum = pgEnum('audit_action', [
  'create',
  'read',
  'update',
  'soft_delete',
  'hard_delete',
  'login',
  'logout',
  'consent_grant',
  'consent_withdraw',
  'document_upload',
  'document_download',
  'export',
]);

export const notificationChannelEnum = pgEnum('notification_channel', ['email', 'sms', 'whatsapp']);

export const notificationStatusEnum = pgEnum('notification_status', [
  'queued',
  'sent',
  'failed',
  'dlq',
]);

// ─── Identity & users ──────────────────────────────────────────────────────────

export const users = pgTable(
  'users',
  {
    id: text('id').primaryKey(), // ULID
    email: text('email').notNull(),
    emailNormalized: text('email_normalized').notNull(), // lowercased, trimmed
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
    passwordHash: text('password_hash'), // null = OAuth-only account
    role: roleEnum('role').notNull().default('patient'),
    locale: localeEnum('locale').notNull().default('tr'),
    failedLoginCount: integer('failed_login_count').notNull().default(0),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => ({
    emailNormalizedUnique: uniqueIndex('users_email_normalized_unique').on(t.emailNormalized),
    roleIdx: index('users_role_idx').on(t.role),
  }),
);

export const oauthAccounts = pgTable(
  'oauth_accounts',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(), // 'google' for now
    providerAccountId: text('provider_account_id').notNull(),
    email: text('email').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    providerAccountUnique: uniqueIndex('oauth_provider_account_unique').on(
      t.provider,
      t.providerAccountId,
    ),
    userIdx: index('oauth_user_idx').on(t.userId),
  }),
);

// WebAuthn passkeys (admin/staff 2FA — patients optional)
export const webauthnCredentials = pgTable('webauthn_credentials', {
  id: text('id').primaryKey(), // credential id from authenticator
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  publicKey: text('public_key').notNull(),
  counter: integer('counter').notNull().default(0),
  transports: jsonb('transports').$type<string[]>(),
  label: text('label'), // user-facing nickname
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
});

// ─── Patient profile ───────────────────────────────────────────────────────────

export const patients = pgTable(
  'patients',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .unique()
      .references(() => users.id, { onDelete: 'restrict' }),
    fullName: text('full_name').notNull(),
    dateOfBirth: date('date_of_birth').notNull(),
    gender: text('gender'), // free text — never inferred
    phoneE164: text('phone_e164'),
    addressLine1: text('address_line1'),
    addressLine2: text('address_line2'),
    city: text('city'),
    postalCode: text('postal_code'),
    countryIso2: text('country_iso2').notNull().default('TR'),
    emergencyContactName: text('emergency_contact_name'),
    emergencyContactPhoneE164: text('emergency_contact_phone_e164'),
    guardianPatientId: text('guardian_patient_id').references((): AnyPgColumn => patients.id),
    notesInternal: text('notes_internal'), // staff-only; never returned to patient API
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => ({
    userUnique: uniqueIndex('patients_user_unique').on(t.userId),
    guardianIdx: index('patients_guardian_idx').on(t.guardianPatientId),
  }),
);

// ─── Doctors & clinic ──────────────────────────────────────────────────────────

export const doctors = pgTable('doctors', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }), // doctor login (optional)
  fullName: text('full_name').notNull(), // 'Uzm. Dr. Oğuz Bak'
  titleShort: text('title_short').notNull().default('Uzm. Dr.'),
  primarySpecialty: text('primary_specialty').notNull().default('Nöroloji'),
  subSpecialty: text('sub_specialty').default('Algoloji'),
  bio: text('bio'),
  photoUrl: text('photo_url'),
  schemaJsonLd: jsonb('schema_json_ld'), // Physician schema cached
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
});

export const clinics = pgTable('clinics', {
  id: text('id').primaryKey(),
  brandName: text('brand_name').notNull(), // 'AĞRI ve KRONİK HASTALIKLAR KLİNİĞİ'
  addressLine1: text('address_line1').notNull(),
  addressLine2: text('address_line2'),
  district: text('district').notNull(),
  city: text('city').notNull(),
  postalCode: text('postal_code'),
  countryIso2: text('country_iso2').notNull().default('TR'),
  geoLat: text('geo_lat'),
  geoLng: text('geo_lng'),
  phoneE164: text('phone_e164').notNull(),
  whatsappE164: text('whatsapp_e164'),
  email: text('email'),
  hoursJson: jsonb('hours_json'), // { mon: [['09:00','18:00']], ... }
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
});

// Doctor's certificates (the "22 certificates" — placeholder rows initially)
export const certificates = pgTable('certificates', {
  id: text('id').primaryKey(),
  doctorId: text('doctor_id')
    .notNull()
    .references(() => doctors.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  issuer: text('issuer'),
  issuedYear: smallint('issued_year'),
  imageUrl: text('image_url'),
  displayOnSite: boolean('display_on_site').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

// ─── Service catalogue (modality + condition cross-axis) ───────────────────────

export const services = pgTable(
  'services',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(), // 'noral-terapi-konsultasyonu'
    pillar: text('pillar').notNull(), // 'integrative_neurology' | 'tms' | 'algoloji' | ...
    durationMinutes: integer('duration_minutes').notNull(),
    deliveryModes: jsonb('delivery_modes')
      .$type<Array<'in_person' | 'home_visit' | 'telehealth'>>()
      .notNull(),
    requiresTmsScreening: boolean('requires_tms_screening').notNull().default(false),
    minPatientAgeYears: smallint('min_patient_age_years').notNull().default(1),
    maxPatientAgeYears: smallint('max_patient_age_years'),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    slugUnique: uniqueIndex('services_slug_unique').on(t.slug),
    pillarIdx: index('services_pillar_idx').on(t.pillar),
  }),
);

export const serviceTranslations = pgTable(
  'service_translations',
  {
    serviceId: text('service_id')
      .notNull()
      .references(() => services.id, { onDelete: 'cascade' }),
    locale: localeEnum('locale').notNull(),
    title: text('title').notNull(),
    leadParagraph: text('lead_paragraph'),
    bodyMarkdown: text('body_markdown'),
    metaDescription: text('meta_description'),
    slugLocalised: text('slug_localised'), // e.g., 'noral-terapi' (tr), 'neural-therapy' (en)
  },
  (t) => ({
    pk: primaryKey({ columns: [t.serviceId, t.locale] }),
    slugLocalisedIdx: index('service_translations_slug_idx').on(t.locale, t.slugLocalised),
  }),
);

export const conditions = pgTable(
  'conditions',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    icd10: text('icd10'),
    pillar: text('pillar').notNull(),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({ slugUnique: uniqueIndex('conditions_slug_unique').on(t.slug) }),
);

export const conditionTranslations = pgTable(
  'condition_translations',
  {
    conditionId: text('condition_id')
      .notNull()
      .references(() => conditions.id, { onDelete: 'cascade' }),
    locale: localeEnum('locale').notNull(),
    title: text('title').notNull(),
    leadParagraph: text('lead_paragraph'),
    bodyMarkdown: text('body_markdown'),
    metaDescription: text('meta_description'),
    slugLocalised: text('slug_localised'),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.conditionId, t.locale] }),
    slugLocalisedIdx: index('condition_translations_slug_idx').on(t.locale, t.slugLocalised),
  }),
);

// Many-to-many: which services are offered for which conditions
export const serviceConditions = pgTable(
  'service_conditions',
  {
    serviceId: text('service_id')
      .notNull()
      .references(() => services.id, { onDelete: 'cascade' }),
    conditionId: text('condition_id')
      .notNull()
      .references(() => conditions.id, { onDelete: 'cascade' }),
    isPrimary: boolean('is_primary').notNull().default(false),
  },
  (t) => ({ pk: primaryKey({ columns: [t.serviceId, t.conditionId] }) }),
);

// ─── Slot availability ─────────────────────────────────────────────────────────

// Recurring slot rules (e.g., "Mon-Fri 14:00-18:00, 30-min slots, in-person consultation")
export const slotTemplates = pgTable('slot_templates', {
  id: text('id').primaryKey(),
  doctorId: text('doctor_id')
    .notNull()
    .references(() => doctors.id, { onDelete: 'restrict' }),
  serviceId: text('service_id')
    .notNull()
    .references(() => services.id, { onDelete: 'restrict' }),
  daysOfWeek: jsonb('days_of_week').$type<number[]>().notNull(), // [1..7], ISO
  startTime: text('start_time').notNull(), // 'HH:MM' clinic-local
  endTime: text('end_time').notNull(),
  slotDurationMinutes: integer('slot_duration_minutes').notNull(),
  bufferMinutes: integer('buffer_minutes').notNull().default(0),
  validFrom: date('valid_from').notNull(),
  validUntil: date('valid_until'),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

// Blackout dates (vacation, conference, hospital duty)
export const slotBlackouts = pgTable('slot_blackouts', {
  id: text('id').primaryKey(),
  doctorId: text('doctor_id')
    .notNull()
    .references(() => doctors.id, { onDelete: 'cascade' }),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  reasonInternal: text('reason_internal'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

// One-off explicit slot offers (e.g., admin opens an extra TMS slot)
export const slotOverrides = pgTable('slot_overrides', {
  id: text('id').primaryKey(),
  doctorId: text('doctor_id')
    .notNull()
    .references(() => doctors.id, { onDelete: 'cascade' }),
  serviceId: text('service_id')
    .notNull()
    .references(() => services.id, { onDelete: 'restrict' }),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  durationMinutes: integer('duration_minutes').notNull(),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

// ─── Appointments ──────────────────────────────────────────────────────────────

export const appointments = pgTable(
  'appointments',
  {
    id: text('id').primaryKey(),
    patientId: text('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),
    doctorId: text('doctor_id')
      .notNull()
      .references(() => doctors.id, { onDelete: 'restrict' }),
    serviceId: text('service_id')
      .notNull()
      .references(() => services.id, { onDelete: 'restrict' }),
    deliveryMode: deliveryModeEnum('delivery_mode').notNull(),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
    status: appointmentStatusEnum('status').notNull().default('created'),
    locale: localeEnum('locale').notNull(),
    patientNotes: text('patient_notes'),
    homeAddressLine1: text('home_address_line1'),
    homeAddressLine2: text('home_address_line2'),
    telehealthRoomId: text('telehealth_room_id'), // Jitsi room
    telehealthJoinUrl: text('telehealth_join_url'),
    telehealthExpiresAt: timestamp('telehealth_expires_at', { withTimezone: true }),
    rescheduledFromAppointmentId: text('rescheduled_from_appointment_id'),
    cancelReason: text('cancel_reason'),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    correlationId: text('correlation_id').notNull(),
    idempotencyKey: text('idempotency_key'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    // The DO is the primary conflict guard, but a DB unique guards against any DO bypass
    doctorSlotUnique: uniqueIndex('appointments_doctor_slot_unique')
      .on(t.doctorId, t.startsAt)
      .where(
        sql`status NOT IN ('cancelled_by_patient','cancelled_by_clinic','late_cancellation','no_show')`,
      ),
    patientIdx: index('appointments_patient_idx').on(t.patientId),
    statusIdx: index('appointments_status_idx').on(t.status),
    startsAtIdx: index('appointments_starts_at_idx').on(t.startsAt),
    idempotencyUnique: uniqueIndex('appointments_idempotency_unique')
      .on(t.idempotencyKey)
      .where(sql`idempotency_key IS NOT NULL`),
  }),
);

export const appointmentStatusHistory = pgTable('appointment_status_history', {
  id: text('id').primaryKey(),
  appointmentId: text('appointment_id')
    .notNull()
    .references(() => appointments.id, { onDelete: 'cascade' }),
  fromStatus: appointmentStatusEnum('from_status'),
  toStatus: appointmentStatusEnum('to_status').notNull(),
  actorUserId: text('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  reason: text('reason'),
  at: timestamp('at', { withTimezone: true }).notNull().default(sql`now()`),
});

// ─── TMS pre-screening ─────────────────────────────────────────────────────────

export const tmsScreenings = pgTable(
  'tms_screenings',
  {
    id: text('id').primaryKey(),
    patientId: text('patient_id')
      .notNull()
      .references(() => patients.id, { onDelete: 'restrict' }),
    doctorId: text('doctor_id')
      .notNull()
      .references(() => doctors.id, { onDelete: 'restrict' }),
    answersJson: jsonb('answers_json').notNull(), // structured Q&A
    status: tmsScreeningStatusEnum('status').notNull().default('pending_review'),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    decidedByUserId: text('decided_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    decisionNotes: text('decision_notes'),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({ patientIdx: index('tms_screenings_patient_idx').on(t.patientId, t.status) }),
);

// ─── KVKK consent records (immutable; new version supersedes old) ──────────────

export const consentDocuments = pgTable('consent_documents', {
  id: text('id').primaryKey(),
  purpose: consentPurposeEnum('purpose').notNull(),
  version: text('version').notNull(), // 'v1.2026-04'
  locale: localeEnum('locale').notNull(),
  bodyMarkdown: text('body_markdown').notNull(),
  publishedAt: timestamp('published_at', { withTimezone: true }).notNull().default(sql`now()`),
});

export const consentRecords = pgTable(
  'consent_records',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    purpose: consentPurposeEnum('purpose').notNull(),
    consentDocumentId: text('consent_document_id')
      .notNull()
      .references(() => consentDocuments.id, { onDelete: 'restrict' }),
    granted: boolean('granted').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    locale: localeEnum('locale').notNull(),
    grantedAt: timestamp('granted_at', { withTimezone: true }).notNull().default(sql`now()`),
    withdrawnAt: timestamp('withdrawn_at', { withTimezone: true }),
  },
  (t) => ({
    userPurposeIdx: index('consent_records_user_purpose_idx').on(t.userId, t.purpose),
  }),
);

// ─── Patient documents (R2-backed) ─────────────────────────────────────────────

export const patientDocuments = pgTable('patient_documents', {
  id: text('id').primaryKey(),
  patientId: text('patient_id')
    .notNull()
    .references(() => patients.id, { onDelete: 'restrict' }),
  uploadedByUserId: text('uploaded_by_user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'restrict' }),
  filename: text('filename').notNull(),
  mimeType: text('mime_type').notNull(),
  mimeKind: documentMimeKindEnum('mime_kind').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  r2Key: text('r2_key').notNull(),
  scanStatus: documentScanStatusEnum('scan_status').notNull().default('pending'),
  scanCompletedAt: timestamp('scan_completed_at', { withTimezone: true }),
  description: text('description'),
  appointmentId: text('appointment_id').references(() => appointments.id, {
    onDelete: 'set null',
  }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
});

// ─── Testimonials ──────────────────────────────────────────────────────────────

export const testimonials = pgTable('testimonials', {
  id: text('id').primaryKey(),
  patientId: text('patient_id').references(() => patients.id, { onDelete: 'set null' }),
  displayName: text('display_name').notNull().default('Hasta Yorumu'),
  locale: localeEnum('locale').notNull(),
  quoteMarkdown: text('quote_markdown').notNull(),
  conditionId: text('condition_id').references(() => conditions.id, { onDelete: 'set null' }),
  serviceId: text('service_id').references(() => services.id, { onDelete: 'set null' }),
  mediaR2Keys: jsonb('media_r2_keys').$type<string[]>(),
  consentRecordId: text('consent_record_id')
    .notNull()
    .references(() => consentRecords.id, { onDelete: 'restrict' }),
  status: testimonialStatusEnum('status').notNull().default('submitted'),
  submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().default(sql`now()`),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  approvedByUserId: text('approved_by_user_id').references(() => users.id, {
    onDelete: 'set null',
  }),
  retractedAt: timestamp('retracted_at', { withTimezone: true }),
});

// ─── CMS-lite content ──────────────────────────────────────────────────────────

export const contentEntries = pgTable(
  'content_entries',
  {
    id: text('id').primaryKey(),
    type: contentEntryTypeEnum('type').notNull(),
    slug: text('slug').notNull(),
    status: contentEntryStatusEnum('status').notNull().default('draft'),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    authorUserId: text('author_user_id').references(() => users.id, { onDelete: 'set null' }),
    reviewerUserId: text('reviewer_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    schemaJsonLd: jsonb('schema_json_ld'),
    relatedConditionId: text('related_condition_id').references(() => conditions.id, {
      onDelete: 'set null',
    }),
    relatedServiceId: text('related_service_id').references(() => services.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    typeSlugUnique: uniqueIndex('content_entries_type_slug_unique').on(t.type, t.slug),
    statusIdx: index('content_entries_status_idx').on(t.status, t.publishedAt),
  }),
);

export const contentEntryTranslations = pgTable(
  'content_entry_translations',
  {
    contentEntryId: text('content_entry_id')
      .notNull()
      .references(() => contentEntries.id, { onDelete: 'cascade' }),
    locale: localeEnum('locale').notNull(),
    title: text('title').notNull(),
    leadParagraph: text('lead_paragraph'),
    bodyMarkdown: text('body_markdown').notNull(),
    metaDescription: text('meta_description'),
    ogImageR2Key: text('og_image_r2_key'),
    doctorNoteMarkdown: text('doctor_note_markdown'), // first-party voice pull-quote
    slugLocalised: text('slug_localised').notNull(),
    readingMinutes: smallint('reading_minutes'),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.contentEntryId, t.locale] }),
    slugLocalisedIdx: index('content_entry_translations_slug_idx').on(t.locale, t.slugLocalised),
  }),
);

// ─── Notifications outbox (idempotent, retryable) ──────────────────────────────

export const notifications = pgTable(
  'notifications',
  {
    id: text('id').primaryKey(),
    channel: notificationChannelEnum('channel').notNull(),
    toUserId: text('to_user_id').references(() => users.id, { onDelete: 'set null' }),
    toEmail: text('to_email'),
    toPhoneE164: text('to_phone_e164'),
    locale: localeEnum('locale').notNull(),
    template: text('template').notNull(), // 'appointment_confirmation' | 'reminder_24h' | ...
    payloadJson: jsonb('payload_json').notNull(),
    status: notificationStatusEnum('status').notNull().default('queued'),
    attempts: integer('attempts').notNull().default(0),
    lastError: text('last_error'),
    appointmentId: text('appointment_id').references(() => appointments.id, {
      onDelete: 'set null',
    }),
    correlationId: text('correlation_id').notNull(),
    scheduledFor: timestamp('scheduled_for', { withTimezone: true }).notNull().default(sql`now()`),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    statusScheduledIdx: index('notifications_status_scheduled_idx').on(t.status, t.scheduledFor),
    appointmentIdx: index('notifications_appointment_idx').on(t.appointmentId),
  }),
);

// ─── Append-only audit log (KVKK Article 12) ───────────────────────────────────

export const auditLog = pgTable(
  'audit_log',
  {
    id: text('id').primaryKey(),
    actorUserId: text('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
    actorRole: roleEnum('actor_role'),
    action: auditActionEnum('action').notNull(),
    entityType: text('entity_type').notNull(), // 'patient', 'appointment', etc.
    entityId: text('entity_id').notNull(),
    targetUserId: text('target_user_id').references(() => users.id, {
      onDelete: 'set null',
    }), // whose data was touched
    correlationId: text('correlation_id').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    metadataJson: jsonb('metadata_json'),
    at: timestamp('at', { withTimezone: true }).notNull().default(sql`now()`),
  },
  (t) => ({
    targetUserIdx: index('audit_log_target_user_idx').on(t.targetUserId, t.at),
    entityIdx: index('audit_log_entity_idx').on(t.entityType, t.entityId),
    actorIdx: index('audit_log_actor_idx').on(t.actorUserId, t.at),
  }),
);

// ─── Webhook idempotency (incoming events) ─────────────────────────────────────

export const webhookEvents = pgTable(
  'webhook_events',
  {
    id: text('id').primaryKey(),
    provider: text('provider').notNull(), // 'meta_whatsapp' | 'resend' | 'netgsm'
    externalId: text('external_id').notNull(),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().default(sql`now()`),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    payloadJson: jsonb('payload_json').notNull(),
  },
  (t) => ({
    providerExternalUnique: uniqueIndex('webhook_events_provider_external_unique').on(
      t.provider,
      t.externalId,
    ),
  }),
);

// ─── Chat (Tier-2 AI assistant) ──────────────────────────────────────────────

export const chatSurfaceEnum = pgEnum('chat_surface', ['whatsapp', 'web']);
export const chatRoleEnum = pgEnum('chat_role', ['user', 'assistant', 'tool']);

export const chatSessions = pgTable('chat_sessions', {
  id: text('id').primaryKey(),
  surface: chatSurfaceEnum('surface').notNull(),
  patientId: text('patient_id').references(() => patients.id, {
    onDelete: 'set null',
  }),
  anonSessionId: text('anon_session_id'),
  waPhoneE164: text('wa_phone_e164'),
  locale: localeEnum('locale').notNull(),
  consentVersion: text('consent_version').notNull(),
  consentGrantedAt: timestamp('consent_granted_at', { withTimezone: true })
    .notNull()
    .default(sql`now()`),
  humanTakeoverUntil: timestamp('human_takeover_until', { withTimezone: true }),
  tokensInTotal: integer('tokens_in_total').notNull().default(0),
  tokensOutTotal: integer('tokens_out_total').notNull().default(0),
  costKurusTotal: integer('cost_kurus_total').notNull().default(0),
  lastMessageAt: timestamp('last_message_at', { withTimezone: true }).notNull().default(sql`now()`),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

export const chatMessages = pgTable('chat_messages', {
  id: text('id').primaryKey(),
  sessionId: text('session_id')
    .notNull()
    .references(() => chatSessions.id, { onDelete: 'cascade' }),
  role: chatRoleEnum('role').notNull(),
  bodyCiphertext: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('body_ciphertext').notNull(),
  bodyIv: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('body_iv').notNull(),
  bodyTag: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('body_tag').notNull(),
  toolName: text('tool_name'),
  toolArgsCiphertext: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('tool_args_ciphertext'),
  toolArgsIv: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('tool_args_iv'),
  toolArgsTag: customType<{ data: Uint8Array; driverData: Buffer }>({
    dataType: () => 'bytea',
    fromDriver: (v) => new Uint8Array(v as Buffer),
    toDriver: (v) => Buffer.from(v),
  })('tool_args_tag'),
  tokensIn: integer('tokens_in'),
  tokensOut: integer('tokens_out'),
  model: text('model'),
  stopReason: text('stop_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().default(sql`now()`),
});

export const chatDailySpend = pgTable('chat_daily_spend', {
  patientId: text('patient_id')
    .notNull()
    .references(() => patients.id, { onDelete: 'cascade' }),
  ymd: date('ymd').notNull(),
  messages: integer('messages').notNull().default(0),
  costKurus: integer('cost_kurus').notNull().default(0),
});

// ─── Type exports for use in domain/infrastructure ─────────────────────────────

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Patient = typeof patients.$inferSelect;
export type NewPatient = typeof patients.$inferInsert;
export type Doctor = typeof doctors.$inferSelect;
export type Service = typeof services.$inferSelect;
export type Condition = typeof conditions.$inferSelect;
export type Appointment = typeof appointments.$inferSelect;
export type NewAppointment = typeof appointments.$inferInsert;
export type ConsentRecord = typeof consentRecords.$inferSelect;
export type NewConsentRecord = typeof consentRecords.$inferInsert;
export type PatientDocument = typeof patientDocuments.$inferSelect;
export type Testimonial = typeof testimonials.$inferSelect;
export type ContentEntry = typeof contentEntries.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type TmsScreening = typeof tmsScreenings.$inferSelect;
